config/routes.rb
Rails.application.routes.draw do

  root 'posts#top'

  resources :users do
    member do
      get 'follow'
      get 'follower'
    end

    collection do
      get 'interpreter'
    end
  end

  resources :posts
  resources :sessions, only: [:new, :create, :destroy]

  resources :conversations do
    resources :messages
  end

  resources :relationships, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :posts, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :name, presence: true, length: { maximum:30 }
  validates :email, uniqueness: true, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :gender, presence: true
  validates :age, presence: true, numericality: { only_integer: true, greater_than: 1 }
  validates :sort, presence: true
  validates :experience, length: { maximum: 150 }

  before_save { email.downcase! }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def self.search(search) #ここでのself.はUser.を意味する
    if search
      where(['name LIKE ?', "%#{search}%"]) #検索とnameの部分一致を表示。User.は省略
    else
      all #全て表示。User.は省略
    end
  end

  # 指定のユーザーをフォローする
  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  # フォローしているかどうかを確認する。
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :forbid_login_user, {only: [:new, :create]}
  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}
  before_action :current_user_check, {only: [:interpreter, :index, :show, :follow, :follower]}

  def index
    @users =
      if params[:search]
        #searchされた場合は、原文+.where('name LIKE ?', "%#{params[:search]}%")を実行
        User.page(params[:page]).where('name LIKE ?', "%#{params[:search]}%").per(12)
      else
        #searchされていない場合は、原文そのまま
        User.page(params[:page]).per(12)
      end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show
    posted_index
    @user = User.find(params[:id])
    @follow = @user.following.count
    @follower = @user.followers.count
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: "退会処理を行いました"
  end

  def interpreter
    @interpreters =
    if params[:search]
      #searchされた場合は、原文+.where('name LIKE ?', "%#{params[:search]}%")を実行
      User.where(sort: 2).page(params[:page]).where('name LIKE ?', "%#{params[:search]}%").per(12)
    else
      #searchされていない場合は、原文そのまま
      User.where(sort: 2).page(params[:page]).per(12)
    end
  end

  def follow
    user = User.find(params[:id])
    @users =
    if params[:search]
      user.following.page(params[:page]).where('name LIKE ?', "%#{params[:search]}%").per(12)
    else
      user.following.page(params[:page]).per(12)
    end
  end

  def follower
    user = User.find(params[:id])
    @users =
    if params[:search]
      user.followers.page(params[:page]).where('name LIKE ?', "%#{params[:search]}%").per(12)
    else
      user.followers.page(params[:page]).per(12)
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,:password_confirmaiton,
                                   :gender, :age, :image, :sort, :experience)
    end
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.new(followed_id: user.id) ) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー", class: "btn btn-default btn-xs" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete) do |f| %>
      <%= f.submit "フォロー中", class: "btn btn-primary btn-xs" %>
    <% end %>
  <% end %>
</div>

app/views/users/_form.html.erb
<div class="container">
  <div class="row">
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h3><%= pluralize(@user.errors.count, "件のエラー") %> </h3>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="signup-area form-group col-sm-offset-3 col-sm-6">
      <%= form_with(model: @user, local: true) do |f| %>
        <p>◆ <%= f.label :名前 %></p>
        <p><%= f.text_field :name, size:"60x5", class:"form-control" %></p>
        <p>◆ <%= f.label :年齢 %></p>
        <p><%= f.text_field :age, size:"60x5", class:"form-control" %></p>
        <p>◆ <%= f.label :性別 %>　　<%= f.select :gender, [["男性", "0"], ["女性", "1"], ["その他", "2"]] %></p>
        <p>◆ <%= f.label :ユーザー属性 %>　　
          <%= f.radio_button :sort, "1" %>　一般ユーザーの方　
          <%= f.radio_button :sort, "2" %>　通訳の方
        </p>
        <p>◆ <%= f.label :メールアドレス %></p>
        <p><%= f.email_field :email, size:"60x5", class:"form-control" %></p>
        <p>◆ <%= f.label :パスワード %></p>
        <p><%= f.password_field :password, size:"60x5", class:"form-control" %></p>
        <p>◆ <%= f.label :パスワード確認 %></p>
        <p><%= f.password_field :password_comfirmaiton, size:"60x5", class:"form-control" %></p>
        <p>◆ <%= f.label :ユーザー画像（任意） %></p>
        <p><%= f.file_field :image, id: :user_image %></p>
        <p>◆ <%= f.label :通訳をご選択の方は簡単に経験をご記入下さい %></p>
        <p><%= f.text_area :experience, size: '60x2', class:"form-control" %></p>
        <%= f.submit "登録" , class:"btn btn-primary"%>
        <% if logged_in? %>
          <%= link_to "退会", user_path, method: :delete, data: { confirm: '退会処理を行っていいですか?'}, class: 'btn btn-danger' %>
        <% end %>
      <% end %>
    </div>
  <div>
</div>

app/views/users/_search.html.erb
<p>名前検索</p>
<%= text_field_tag :search %>
<%= submit_tag '検索', :name => nil %>

app/views/users/_users.html.erb
<div class="clearfix">
  <% @users.order(name: :asc).each do |user| %>
    <div class="user-area clearfix">
      <div class="image-area">
        <% if user.image.present? %>
          <%= image_tag user.image_url, :size => '70x70' %>
        <% else %>
          <%= image_tag '/initial.png', :size => '70x70' %>
        <% end %>
      </div>
      <div class="users-user-index">
        <p>
          <%= link_to "#{user.name}さん", user_path(user.id) %>
          <% if user.sort == 2 %>
            <span>
              <%= image_tag '/mark_maru.png', :size => '30x30' %>
            </span>
          <% end %>
        </p>
        <p>性別:
          <% if user.gender == 0 %>
            <%= "男性 "%>
            <% elsif user.gender == 1 %>
              <%= "女性" %>
            <% else %>
              <%= "その他" %>
            <% end %>
          </p>
          <% if current_user.id != user.id %>
            <%= render 'follow_form', user: user %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

app/views/users/edit.html.erb
<h3 style="text-align: center;">編集</h3>
<%= render 'form'%>

app/views/users/follow.html.erb
<h4 class="title">フォロー</h4>
<div class="container">
  <div class="row">
    <div class="col-sm-offset-1 col-sm-10" style="margin-bottom: 20px;">
      <%= render 'users' %>
      <%= paginate @users %>
    </div>
    <div class="row"></div>
  </div>
</div>

app/views/users/follower.html.erb
<h4 class="title">フォロワー</h4>
<div class="container">
  <div class="row">
    <div class="col-sm-offset-1 col-sm-10" style="margin-bottom: 20px;">
      <%= render 'users' %>
      <%= paginate @users %>
    </div>
    <div class="row"></div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-1 col-sm-10" style="margin-bottom: 20px;">
      <p class="switching-btn"><%= link_to "通訳者のみ表示", interpreter_users_path, class:"btn btn-info btn-md" %></p>
      <%= form_tag(users_path, method: :get, style:"padding-bottom: 20px;") do %>
        <%= render 'search' %>
      <% end %>
      <%= page_entries_info @users %>
      <%= render 'users' %>
      <%= paginate @users %>
    </div>
    <div class="row"></div>
  </div>
</div>

app/views/users/interpreter.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-1 col-sm-10" style="margin-bottom: 20px;">
      <p class="switching-btn"><%= link_to "全てのユーザーを表示", users_path, class:"btn btn-info btn-md" %></p>
      <%= form_tag(interpreter_users_path, method: :get, style:"padding-bottom: 20px;") do %>
        <%= render 'search' %>
      <% end %>
      <%= page_entries_info @interpreters %>
      <div class="clearfix">
        <% @interpreters.order(name: :asc).each do |interpreter| %>
          <div class="interpreter-area clearfix">
            <div class="image-area">
              <% if interpreter.image.present? %>
                <%= image_tag interpreter.image_url, :size => '70x70' %>
              <% else %>
                <%= image_tag '/initial.png', :size => '70x70' %>
              <% end %>
            </div>
            <div class="users-user-index">
              <p>
                <%= link_to "#{interpreter.name}さん", user_path(interpreter.id) %>
                <span>　<%= image_tag '/mark_maru.png', :size => '30x30' %></span>
              </p>
              <p>性別:
                <% if interpreter.gender == 0 %>
                  <%= "男性 "%>
                  <% elsif interpreter.gender == 1%>
                    <%= "女性" %>
                  <% else %>
                    <%= "その他" %>
                  <% end %>
                </p>
                <%= render 'follow_form', user: interpreter %>
              </div>
            </div>
          <% end %>
        </div>
        <%= paginate @interpreters %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h3 style="text-align: center;">会員登録画面</h3>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <h3>プロフィール</h3>
    <div class="user-self-area col-xs-5 col-sm-4">
      <div class="user-box1 clearfix">
        <div class="image-area">
          <% if @user.image.present? %>
            <%= image_tag @user.image_url, :size => '70x70' %>
          <% else %>
            <%= image_tag '/initial.png', :size => '70x70' %>
          <% end %>
        </div>
        <div class="users-user-info">
          <p><%= render 'follow_form', user: @user %></p>
          <p>名前: <%= @user.name %></p>
          <p>年齢: <%= @user.age %></p>
          <p>性別:
            <% if @user.gender == 0 %>
              <%= "男性 "%>
            <% elsif @user.gender == 1%>
              <%= "女性" %>
            <% else %>
              <%= "その他" %>
            <% end %>
          </p>
          <p>ユーザー属性:
            <% if @user.sort == 1 %>
              <%= "一般ユーザー" %>
            <% else %>
              <%= "通訳者" %>　<%= image_tag '/mark_maru.png', :size => '35x35' %>
            <% end %>
          </p>
            <% if current_user.id == @user.id %>
              <p><%= link_to "メッセージ一履歴", conversations_path %></p>
            <% end %>
          </div>
        </div>
        <div class="clearfix">
          <div style="float: left;">
            <% if logged_in? && current_user.id != @user.id  %>
              <%= link_to image_tag('/message.png'), conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: :post %>
            <% elsif current_user.id == @user.id %>
              <%= link_to "編集", edit_user_path(@user.id), class: 'btn btn-default btn-sm' %>
            <% end %>
          </div>
          <div class="follow-count">
            <%= link_to "フォロー：#{@follow}人", follow_user_path(@user.id) %>
          </div>
          <div class="follow-count">
            <%= link_to "フォロワー：#{@follower}人", follower_user_path(@user.id) %>
          </div>
        </div>
        <div class="experience-area">
          <% if @user.experience.present? %>
            <p style="font-size: 15px">手話経験</p>
            <p style="word-break:break-all; word-wrap:break-word; display: inline-block; ">
              <%= @user.experience %>
            </p>
          <% end %>
        </div>
      </div>
      <!-- ここまでプロフィールエリア -->

      <div class="content-area col-xs-7 col-sm-offset-1 col-sm-6">
        <h3>投稿履歴</h3>
        <p class="page-entries-info clearfix"><%= page_entries_info @user_posted %></p>
        <% @user_posted.each do |post| %>
          <div class="post-content">
            <p>タイトル: <%= link_to cut_off("#{post.title}", 20), post_path(post.id) %></p>
            <p>希望日: <%= simple_time post.requested_date %></p>
            <p>投稿日: <%= simple_time post.created_at %></p>
          </div>
        <% end %>
        <%= paginate @user_posted %>
      </div>
    </div>
  </div>