config/routes.rb
Rails.application.routes.draw do

  root 'posts#top'

  resources :users do
    member do
      get 'follow'
      get 'follower'
    end

    collection do
      get 'interpreter'
    end
  end

  resources :posts
  resources :sessions, only: [:new, :create, :destroy]

  resources :conversations do
    resources :messages
  end

  resources :relationships, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  validates :title, presence: true
  validates :requested_date, presence: true
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :current_user_check, only: [:new, :edit, :show, :destroy]

  def index
    @posts =
      if params[:search]
        Post.page(params[:page]).per(10).where('title LIKE ?', "%#{params[:search]}").includes(:user)
      else
        #searchされていない場合は、原文そのまま
        Post.page(params[:page]).per(10).includes(:user)
      end

    @post = Post.new
    user_find if current_user
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, notice: "投稿しました"
    else
      redirect_to posts_path, notice: "投稿できませんでした"
    end
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "編集しました"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "削除しました"
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :requested_date, :user_id)
    end

    def set_post
      @post = Post.find(params[:id])
    end

end

app/views/posts/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-2 col-sm-8">
      <%= form_with(model: @post, local: true) do |f| %>
        <div class="post-form form-group">
          <% if @post.errors.any? %>
            <div id="error_explanation">
              <h2><%= @post.errors.count %>件のエラーがあります。</h2>
              <ul>
                <% @post.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
            <div class="form-area">
              <p><%= f.label :タイトル%></p>
              <p><%= f.text_area :title, class:"form-control" %></p>
              <p><%= f.label :希望日 %></p>
              <p><%= raw sprintf( f.datetime_select( :requested_date, discard_minute: true, discard_hour: true, use_month_numbers: true, date_separator: '%s'), '年', '月') + '日' %></p>
              <p><%= f.label :依頼内容 %></p>
              <p><%= f.text_area :content, class:"form-control" %></p>
            <div class="submit-button">
              <%= f.submit :保存, data: { confirm: '投稿していいですか?'}, class:"btn btn-primary" %>
              <%= link_to "戻る", posts_path, class:"btn btn-default" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h3 style="text-align: center;">編集</h3>
<%= render "form" %>

app/views/posts/index.html.erb
<div class="main-page clearfix container">
  <div class="row">
    <% if current_user %>
      <div class="post-self-area col-xs-3">
        <% if logged_in? && current_user.id != @user.id  %>
          <h4 class="send-message">
            <%= link_to "メッセージを送る", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: :post %>
          </h4>
        <% end %>
        <div class="user-box1 clearfix">
          <div class="image-area">
            <% if @user.image.present? %>
              <%= image_tag @user.image_url, :size => '70x70' %>
            <% else %>
              <%= image_tag '/initial.png', :size => '70x70' %>
            <% end %>
          </div>
          <div class="posts-user-info">
            <p>
              <strong>名前：<%= @user.name %></strong>
            </p>
            <p><%= link_to "マイページ", user_path(@user.id) %></p>
              <% if current_user.id == @user.id %>
                <span><%= link_to "メッセージ履歴", conversations_path %></span>
              <% end %>
          </div>
        </div>

        <!-- ここから投稿フォーム -->
        <div class="post-area form-group">
          <%= form_with(model: @post, local: true) do |f| %>
            <% if @post.errors.any? %>
              <div id="error_explanation">
              <h2><%= @post.errors.count %>件のエラーがあります。</h2>
                <ul>
                  <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

          <div class="form-area">
            <p><%= f.label :タイトル%></p>
            <p><%= f.text_area :title, :size => '10x2', class:"form-control" %></p>
            <p><%= f.label :希望日 %></p>
            <p><%= raw sprintf( f.datetime_select( :requested_date, discard_minute: true, discard_hour: true, use_month_numbers: true, date_separator: '%s'), '年', '月') + '日' %></p>
            <p><%= f.label :依頼内容 %></p>
            <p><%= f.text_area :content, :size => '10x5', class:"form-control" %></p>
            <p class="submit-button">
              <%= f.submit :投稿, data: { confirm: '投稿していいですか?'}, class:"btn btn-primary", size:"32x5;"%>
            </p>
          </div>
        </div>
        <% end %> <!-- form_withの終了タグ -->
       </div>


    <% else %>  <!-- ログインしていないときのフォーム -->
      <div class="empty-box col-xs-3">
        <h4><%= link_to "新規会員登録", new_user_path %></h4>
      </div>
    <% end %>




    <!-- ここから投稿一覧エリア -->
      <div class="content-area  col-xs-8 col-sm-offset-1 col-sm-7">
        <h3>投稿一覧</h3>
        <%= form_tag(posts_path, method: :get, style:"padding-bottom: 20px;") do %>
          <p>タイトル検索</p>
          <%= text_field_tag :search %>
          <%= submit_tag '検索', :name => nil %>
        <% end %>
        <p class="page-entries-info clearfix"><%= page_entries_info @posts %></p>

        <% @posts.reverse_order.each do |post|%>
        <div class="post-content clearfix">
          <div class="image-area">
            <% if post.user.image.present? %>
              <%= image_tag post.user.image_url, :size => '70x70' %>
            <% else %>
              <%= image_tag '/initial.png', :size => '70x70' %>
            <% end %>
          </div>
          <div class="post-info">
            <p>投稿者:
              <%= link_to " #{post.user.name} さん", user_path(post.user_id) %>　
              <% if post.user.sort == 2 %>
              <span>
                <%= image_tag '/mark_maru.png', :size => '30x30' %>
              </span>
              <% end %>
            </p>
            <p>タイトル:
              <%= link_to cut_off("#{post.title}", 20), post_path(post.id) %>
            </p>
            <p>希望日:
              <%= simple_time post.requested_date %>
            </p>
            <p>投稿日:
              <%= simple_time post.created_at %>
            </p>
          </div>
          <% if post.user == current_user %>
            <div class="edit-destroy-button">
              <%= link_to image_tag('/edit.png'), edit_post_path(post.id) %>
              <%= link_to image_tag('/trash.png'), post, method: :delete, data: { confirm: '削除していいですか?'} %>
            </div>
          <% end %>
        </div>
      <% end %>
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-1 col-sm-10">
      <h3>投稿内容</h3>
      <div class="post-show-area clearfix">
        <div class="image-area">
          <% if @post.user.image.present? %>
            <%= image_tag @post.user.image_url, :size => '70x70' %>
          <% else %>
            <%= image_tag '/initial.png', :size => '70x70' %>
          <% end %>
        </div>
        <div class="post-info">
          <p>投稿者:　
            <%= link_to "#{@post.user.name} さん", user_path(@post.user_id) %>　
            <% if @post.user.sort == 2 %>
            <span>
              <%= image_tag '/mark_maru.png', :size => '40x40' %>
            </span>
            <% end %>
          </p>
          <p>タイトル</p>
          <p><%= "#{@post.title}" %></p>
          <p>内容</p>
          <p><%= @post.content %></p>
          <p>希望日:　<%= simple_time @post.requested_date %></p>
          <p>投稿日:　<%= simple_time @post.created_at %></p>
        </div>
      </div>
        <% if @post.user == current_user %>
          <div class="post_btn_area">
            <%= link_to image_tag('/edit.png'), edit_post_path(@post.id), :size => "10x4" %>
            <%= link_to image_tag('/trash.png'), post, method: :delete, data: { confirm: '削除していいですか?'} %>
          </div>
        <% end %>
        <h5>
          <% if current_user.id != @post.user_id %>
            <%= link_to "#{@post.user.name}さんへメッセージを送る", conversations_path(sender_id: current_user.id, recipient_id: @post.user_id), method: :post %>
          <% end %>
        </h5>
    </div>
  </div>
</div>

app/views/posts/top.html.erb
<h3>test</h3>
<h3><%= link_to "新規登録", new_user_path %></h3>
<h3>サンプルユーザーでもログインできます</h3>
<p>メールアドレス: sample@test.com</p>
<p>パスワード: password</p>