config/routes.rb
Rails.application.routes.draw do

  root 'posts#top'

  resources :users do
    member do
      get 'follow'
      get 'follower'
    end

    collection do
      get 'interpreter'
    end
  end

  resources :posts
  resources :sessions, only: [:new, :create, :destroy]

  resources :conversations do
    resources :messages
  end

  resources :relationships, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>sample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width">
  </head>
  <body>
    <div class="container">
      <header class="header clearfix">
        <h2><%= link_to "sample", posts_path, style:"color: #fff;" %></h2>
        <ul class="nav navbar-nav navbar-right top-menu">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle dropdown-toggle-extend" data-toggle="dropdown" style="color: #fff;">
              アカウント<span class="caret"></span>
            </a>
            <!-- 1.メニューの配置 -->
            <ul class="dropdown-menu dropdown-menu-extend">
              <% if logged_in? %>
                <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
                <li><%= link_to "アカウント編集", edit_user_path(current_user.id) %></li>
                <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
              <% else %>
                <li><%= link_to "ログイン",new_session_path %></li>
                <li><%= link_to "新規登録 ", new_user_path %></li>
              <% end %>
            </ul>
          <li><%= link_to "ユーザー検索", users_path, style:"color: #fff;" %></li>
          <li><%= link_to "トップ", posts_path, style:"color: #fff;" %></li>
        </li>
      </ul>

    </header>
    <div class="wrapper">
      <strong class="flash-area">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
      </strong>
      <%= yield %>
    </div>
    <footer></footer>
  </div>
</body>
</html>